#!/usr/bin/env zsh

# bindkey vim mode
bindkey -v

# Change cursor shape for different vi modes.
function zle-keymap-select () {
    case $KEYMAP in
        vicmd) echo -ne '\e[2 q';;      # block
        viins|main) echo -ne '\e[2 q';; # block (yes in insert mode)
    esac
}
zle -N zle-keymap-select
zle-line-init() {
    zle -K viins # initiate `vi ins` as keymap (can be removed if `bindkey -V` has been set elsewhere)
    echo -ne "\e[2 q"
}
zle -N zle-line-init
echo -ne '\e[2 q' # Use block shape cursor on startup.
preexec() { echo -ne '\e[2 q' ;} # Use block shape cursor for each new prompt.
