#!/usr/bin/env zsh

# Emacs-like bindings
# Movement
bindkey '^B' backward-char
bindkey '^F' forward-char
bindkey '^A' beginning-of-line
bindkey '^E' end-of-line
bindkey '^[b' backward-word
bindkey '^[f' forward-word
bindkey '^P' up-line-or-history
bindkey '^N' down-line-or-history
# Killing and yanking
bindkey '^U' backward-kill-line
bindkey '^O' kill-line
bindkey '^D' delete-char-or-list    # TODO upgrade to cut to clipbaord when in selection mode like in my emacs config
bindkey '^[d' kill-word
bindkey '^H' backward-delete-char   # TODO upgrade to cut to clipbaord when in selection mode like in my emacs config
bindkey '^W' backward-kill-word
bindkey '^Y' yank                   # paste from system clipboard - works fine

# Full keyboard keys
bindkey '^?' backward-delete-char
bindkey '^H' backward-kill-word
bindkey 'Home' beginning-of-line
bindkey 'End' end-of-line
bindkey '^[[1~' beginning-of-line
bindkey '^[[4~' end-of-line
bindkey '^[[1;5C' forward-word
bindkey '^[[1;5D' backward-word
bindkey '^[[A' up-line-or-history
bindkey '^[[B' down-line-or-history
bindkey '^[[5~' beginning-of-buffer-or-history
bindkey '^[[6~' end-of-buffer-or-history
bindkey '^[[3~' delete-char
bindkey '^[[Z' reverse-menu-complete

# Emacs has it's own clipboard buffer which to normally the text is copied, same with zsh
# By default keys M-w for copy and C-y for paste are set in emacs and zsh
# thanks to to my functions I can copy text to system clipboard using M-w and M-W, and paste using C-y

# Copy selected text to clipboard, works fine - bound by default to alt+w
copy-region-as-kill() {
  zle copy-region-as-kill
  print -n $CUTBUFFER | wl-copy           # wl-copy -p -n    # Just suggestion command alternative
}
zle -N copy-region-as-kill

# Copy current line to clipboard
cmd_to_clip () { wl-copy <<< $BUFFER }
zle -N cmd_to_clip
bindkey '^[[W' cmd_to_clip     # Alt+Shift+w

# TODO - EXPERIMENTAL - convert to normal from vi mode (vicmd)
#bindkey -M vicmd '^[.' insert-last-word  # M-.
#bindkey -M vicmd '^[g' get-line          # M-g
#bindkey -M vicmd '^Q' push-line          # C-q
#bindkey '^Z' edit-command-line           # Open in emacs
#bindkey -M visual '^[' '^[v'             # selection-mode
#bindkey -M visual '^[x' '^[x'            # selection-mode

# Selection mode on C-SPC - set by default
#function selection-mode {
#    zle set-mark-command
#    zle vi-match-bracket
#}
#zle -N selection-mode
#bindkey '^ ' selection-mode
