#!/usr/bin/env zsh

# Emacs-like bindings
# Movement
bindkey '^B' backward-char
bindkey '^F' forward-char
bindkey '^A' beginning-of-line
bindkey '^E' end-of-line
bindkey '^[b' backward-word
bindkey '^[f' forward-word
bindkey '^P' up-line-or-history
bindkey '^N' down-line-or-history
# Killing and yanking
bindkey '^U' backward-kill-line
bindkey '^O' kill-line
bindkey '^[d' kill-word
bindkey '^L' insert-last-word
bindkey '^W' backward-kill-word
bindkey '^Y' yank                   # paste from system clipboard - works fine

# Full keyboard keys
bindkey '^?' backward-delete-char
bindkey '^H' backward-kill-word
bindkey 'Home' beginning-of-line
bindkey 'End' end-of-line
bindkey '^[[1~' beginning-of-line
bindkey '^[[4~' end-of-line
bindkey '^[[1;5C' forward-word
bindkey '^[[1;5D' backward-word
bindkey '^[[A' up-line-or-history
bindkey '^[[B' down-line-or-history
bindkey '^[[5~' beginning-of-buffer-or-history
bindkey '^[[6~' end-of-buffer-or-history
bindkey '^[[3~' delete-char
bindkey '^[[Z' reverse-menu-complete

# Emacs has it's own clipboard buffer which to normally the text is copied, same with zsh
# By default keys M-w for copy and C-y for paste are set in emacs and zsh
# thanks to to my functions I can copy text to system clipboard using M-w and M-W, and paste using C-y

# Copy selected text to clipboard, works fine - bound by default to alt+w
copy-region-and-kill() {
  zle copy-region-as-kill
  print -n $CUTBUFFER | wl-copy
}
zle -N copy-region-and-kill
bindkey '^[w' copy-region-and-kill

# Copy current line to clipboard
copy-current-line() {
  print -n "$BUFFER" | wl-copy
}
zle -N copy-current-line
bindkey '^[W' copy-current-line     # Alt+Shift+w

cut-to-clipboard() {
  zle kill-region
  print -n $CUTBUFFER | wl-copy
}
zle -N cut-to-clipboard
bindkey '^D' cut-to-clipboard
bindkey '^H' cut-to-clipboard

scroll-and-clear-screen() {
    printf '\n%.0s' {1..$LINES}
    zle clear-screen
}
zle -N scroll-and-clear-screen
bindkey '^G' scroll-and-clear-screen

# Function for new command
function _new_command {
    zle push-input
    BUFFER=""
}
zle -N _new_command
bindkey '^.' _new_command

# Function to open help page
custom-run-help() {
    LBUFFER="help $LBUFFER"
    zle accept-line
}
zle -N custom-run-help
bindkey '^[h' custom-run-help

# Open in external editor command - not working 
#bindkey '^[g' get-line            # M-g
#bindkey '^X^E' edit-command-line  # Open in emacs
