#!/bin/sh
while read file
do
        case "$1" in
        "C-d")
                mv "$file" ~/.trash ;;
        "C-r")
                convert -rotate 90 "$file" "$file" ;;
        "C-c")
                echo -n "$file" | wl-copy -n ;;
        "C-w")
                swaybg -m fill -i "$file" ;;
        esac
done
