#!/usr/bin/env bash

# Original source: https://bluz71.github.io/2018/11/26/fuzzy-finding-in-bash-with-fzf.html

if [[ $(uname) = Linux ]]; then
	pid_col=2
	pids=$(ps -f -u "$USER" | sed 1d | fzf --multi | tr -s "[:blank:]" | cut -d' ' -f"$pid_col")
else
	echo 'Error: unknown platform'
	return
fi

if [[ -n "$pids" ]]; then
	echo "$pids" | xargs kill -9 "$@"
fi
