#!/bin/bash

is_kitty_running() {
  hyprctl clients | grep 'agenda-kitty' >/dev/null
}

if ! is_kitty_running; then
  hyprctl dispatch exec 'kitty -1 -o confirm_os_window_close=1 -T agenda-kitty --class agenda-kitty --session ~/.config/kitty/session-agenda'
else
  hyprctl dispatch focuswindow 'class:^(agenda-kitty)$'
fi
