#!/bin/bash

# Function to check if bloodhound is running
is_bloodhound_running() {
  hyprctl clients | grep 'bloodhound' >/dev/null
}

# Check if monitor DP-2 is active
if hyprctl monitors | grep -q "Monitor DP-2"; then
    # If DP-2 is active, switch to workspace 11
    hyprctl dispatch workspace 11
else
    # If DP-2 is not active, switch to workspace 4
    hyprctl dispatch workspace 4
fi

# Check if bloodhound is running
if ! is_bloodhound_running; then
  # If bloodhound is not running, launch it
  hyprctl dispatch exec 'bloodhound --no-sandbox'
else
  # If bloodhound is running, focus on its window
  hyprctl dispatch focuswindow 'bloodhound'
fi
