#!/bin/bash
is_kitty_running() {
  hyprctl clients | grep 'blueman-manager' >/dev/null
}
if ! is_kitty_running; then
  hyprctl dispatch 'hl.dsp.exec_cmd([=[uwsm app -- blueman-manager]=])'
else
  hyprctl dispatch 'hl.dsp.workspace.toggle_special("period")'
  hyprctl dispatch 'hl.dsp.focus({window="class:^(blueman-manager)$"})'
fi
