#!/bin/bash

is_kitty_running() {
  hyprctl clients | grep 'blueman-manager' >/dev/null
}

if ! is_kitty_running; then
  hyprctl dispatch exec 'blueman-manager'
else
  hyprctl dispatch togglespecialworkspace period
  hyprctl dispatch focuswindow '^blueman-manager$'
fi
