#!/bin/bash

#is_kitty_running() {
#  hyprctl clients | grep 'brave-browser' >/dev/null
#}
#
#if ! is_kitty_running; then
#  hyprctl dispatch exec 'brave --ignore-gpu-blocklist --enable-gpu-rasterization --enable-zero-copy --disable-gpu-driver-bug-workarounds --ozone-platform-hint=wayland --use-gl=angle --enable-features=VaapiVideoDecoder --enable-features=VaapiIgnoreDriverCheck --disable-features=UseChromeOSDirectVideoDecoder --enable-features=TouchpadOverscrollHistoryNavigation --disable-features=WaylandFractionalScaleV1'
#else
#  hyprctl dispatch focuswindow 'brave-browser'
#fi

is_kitty_running() {
  hyprctl clients | grep 'firedragon' >/dev/null
}

if ! is_kitty_running; then
  hyprctl dispatch exec 'firedragon'
else
  hyprctl dispatch focuswindow 'firedragon'
fi
