#!/bin/bash
is_kitty_running() {
  hyprctl clients | grep 'org.gnome.Calculator' >/dev/null
}
if ! is_kitty_running; then
  hyprctl dispatch 'hl.dsp.exec_cmd([=[uwsm app -- gnome-calculator]=])'
else
  hyprctl dispatch 'hl.dsp.workspace.toggle_special("floating")'
  hyprctl dispatch 'hl.dsp.focus({window="class:^(org.gnome.Calculator)$"})'
fi
