#!/bin/bash

is_kitty_running() {
  hyprctl clients | grep 'org.gnome.Calculator' >/dev/null
}

if ! is_kitty_running; then
  hyprctl dispatch exec 'gnome-calculator'
else
  hyprctl dispatch togglespecialworkspace floating
  hyprctl dispatch focuswindow 'class:^(org.gnome.Calculator)$'
fi
