#!/bin/bash

is_kitty_running() {
  hyprctl clients | grep 'kitty-docs' >/dev/null
}

if ! is_kitty_running; then
  hyprctl dispatch exec 'kitty -1 -T kitty-docs --class kitty-docs --session ~/.config/kitty/session-docs'
else
  hyprctl dispatch focuswindow 'kitty-docs'
fi
