#!/bin/bash

# Function to check if 'kitty' process is running
is_kitty_running() {
	hyprctl clients | grep 'kitty-docs' >/dev/null
}

# Focus on ws "5" and spawn kitty it's not running, else only focus
if ! is_kitty_running; then
    # Spawn 'kitty' only if it was not running
    hyprctl dispatch exec 'kitty -1 -T kitty-docs --class kitty-docs --session ~/.config/kitty/session-docs'
else
    hyprctl dispatch focuswindow 'kitty-docs'
fi
