#!/bin/bash

# Function to check if 'kitty' process is running
is_kitty_running() {
	hyprctl clients | grep 'kitty-emacs' >/dev/null
}

# Focus on ws "4" and spawn kitty it's not running, else only focus
if ! is_kitty_running; then
    # Spawn 'kitty' only if it was not running
    hyprctl dispatch exec 'kitty -1 -T kitty-emacs --class kitty-emacs --session ~/.config/kitty/session-emacs'
else
    hyprctl dispatch focuswindow 'kitty-emacs'
fi
