#!/bin/bash

# Function to check if 'kitty' process is running
is_kitty_running() {
	hyprctl clients | grep 'kitty-code' >/dev/null
}

# Focus on ws "5" and spawn kitty it's not running, else only focus
if ! is_kitty_running; then
    # Spawn 'kitty' only if it was not running
    hyprctl dispatch exec 'kitty -1 -T kitty-code --class kitty-code --session ~/.config/kitty/session-emacs-code'
else
    hyprctl dispatch focuswindow 'kitty-code'
fi
