#!/bin/bash
is_kitty_running() {
  hyprctl clients | grep 'emacs' >/dev/null
}
if ! is_kitty_running; then
  hyprctl dispatch 'hl.dsp.exec_cmd([=[uwsm app -- emacsclient -c]=])'
else
  hyprctl dispatch 'hl.dsp.focus({window="class:^(emacs)$"})'
fi
