#!/bin/bash

is_kitty_running() {
  hyprctl clients | grep 'emacs' >/dev/null
}

if ! is_kitty_running; then
  hyprctl dispatch exec 'uwsm app -- emacsclient -c'
else
  hyprctl dispatch focuswindow 'class:^(emacs)$'
fi
