#!/bin/bash

# Function to check if Netflix is running
is_netflix_running() {
  hyprctl clients | grep 'Ferdium' >/dev/null
}

hyprctl dispatch workspace 6

# Check if netflix is running
if ! is_netflix_running; then
  # If netflix is not running, launch it
  hyprctl dispatch exec 'ferdium --ozone-platform=wayland --enable-features-WaylandWindowDecorations'
else
  # If netflix is running, focus on its window
  hyprctl dispatch focuswindow 'class:^(Ferdium)$'
fi
