#!/bin/bash

# Function to check if 'floorp' process is running for a specific profile
is_floorp_running() {
    pgrep -a "floorp" | grep "$1" >/dev/null
}

# Check if any of the 3 floorp profiles is running then focus it
if is_floorp_running 'default-default'; then
    hyprctl dispatch exec 'floorp -P default-default'
elif is_floorp_running 'default-work'; then
    hyprctl dispatch exec 'floorp -P default-work'
elif is_floorp_running 'default-osint'; then
    hyprctl dispatch exec 'floorp -P default-osint'
else
    hyprctl dispatch focuswindow 'floorp'
fi
