#!/bin/bash

is_kitty_running() {
  hyprctl clients | grep 'FreeTube' >/dev/null
}

if ! is_kitty_running; then
  hyprctl dispatch exec 'freetube --enable-features=WaylandWindowDecorations --ozone-platform-hint=auto --enable-features=VaapiVideoDecodeLinuxGL --gpu-context=wayland'
else
  hyprctl dispatch focuswindow 'FreeTube'
fi
