#!/bin/bash

is_kitty_running() {
  hyprctl clients | grep 'kitty-2' >/dev/null
}

if ! is_kitty_running; then
  hyprctl dispatch exec 'kitty -1 -o confirm_os_window_close=1 -T kitty-2 --class kitty-2'
else
  hyprctl dispatch focuswindow 'kitty-2'
fi
