#!/bin/bash

# Function to check if kitty-1 is running
is_kitty_running() {
  hyprctl clients | grep 'kitty-1' >/dev/null
}

# Check if monitor DP-2 is active
if hyprctl monitors | grep -q "Monitor DP-2"; then
    # If DP-2 is active, switch to workspace 8
    hyprctl dispatch workspace 8
else
    # If DP-2 is not active, switch to workspace 1
    hyprctl dispatch workspace 1
fi

# Check if kitty-1 is running
if ! is_kitty_running; then
  # If kitty-1 is not running, launch it
  hyprctl dispatch exec 'kitty -1 -o confirm_os_window_close=1 -T kitty-1 --class kitty-1 --session ~/.config/kitty/session-1'
else
  # If kitty-1 is running, focus on its window
  hyprctl dispatch focuswindow 'kitty-1'
fi
