#!/bin/bash

# Function to check if 'kitty' process is running
is_kitty_running() {
	hyprctl clients | grep 'kitty-2' >/dev/null
}

# Focus on ws "1" and spawn kitty it's not running, else only focus
if ! is_kitty_running; then
    # Spawn 'kitty' only if it was not running
    hyprctl dispatch exec 'kitty -1 -T kitty-2 --class kitty-2'
else
    hyprctl dispatch focuswindow 'kitty-2'
fi
