#!/bin/bash

# Function to check if 'kitty' process is running
is_kitty_running() {
	hyprctl clients | grep 'kitty-1' >/dev/null
}

# Focus on ws "1" and spawn kitty it's not running, else only focus
if ! is_kitty_running; then
    # Spawn 'kitty' only if it was not running
    hyprctl dispatch exec 'kitty -1 -T kitty-1 --class kitty-1'
else
    hyprctl dispatch focuswindow 'kitty-1'
fi
