#!/bin/bash

is_kitty_running() {
  hyprctl clients | grep 'labs-kitty' >/dev/null
}

if ! is_kitty_running; then
  hyprctl dispatch exec 'kitty -1 -o confirm_os_window_close=0 -T labs-kitty --class labs-kitty --session ~/.config/kitty/session-labs'
else
  hyprctl dispatch focuswindow 'labs-kitty'
fi
