#!/bin/bash

is_kitty_running() {
  hyprctl clients | grep 'kitty-labs-2' >/dev/null
}

if ! is_kitty_running; then
  hyprctl dispatch exec 'kitty -1 -T kitty-labs-2 --class kitty-labs-2 --session ~/.config/kitty/session-labs-2'
else
  hyprctl dispatch focuswindow 'kitty-labs-2'
fi
