#!/bin/bash

# Function to check if 'mullvad' process is running
is_mullvad_running() {
	pgrep -a "mullvad" | grep 'default-default' >/dev/null
}

# Focus on ws "3" if 'mullvad-browser' is not running, else just focus
if ! is_mullvad_running; then
    # Spawn 'mullvad-browser' only if it was not running
    hyprctl dispatch exec 'mullvad-browser -P default-default'
else
    hyprctl dispatch focuswindow 'mullvad-default'
fi
