#!/bin/bash

is_kitty_running() {
  hyprctl clients | grep 'monitoring-kitty' >/dev/null
}

if ! is_kitty_running; then
  hyprctl dispatch exec 'kitty -1 -o confirm_os_window_close=1 -T monitoring-kitty --class monitoring-kitty --session ~/.config/kitty/session-monitoring'
else
  hyprctl dispatch focuswindow 'class:^(monitoring-kitty)$'
fi
