#!/bin/bash

# Function to check if 'newsboat' process is running
is_newsboat_running() {
    prep -x "newsboat" >/dev/null
}

# Focus on ws "6" and spawn 'newsboat' if it's not running, else only focus
if ! is_newsboat_running; then
    # Spawn 'newsboat' only if it was not running
    hyprctl dispatch exec 'footclient -a newsboat -e newsboat'
else
    hyprctl dispatch focuswindow 'newsboat'
fi
