#!/bin/bash

# Function to check if Netflix is running
is_netflix_running() {
  hyprctl clients | grep 'Netflix' >/dev/null
}

# Check if monitor DP-2 is active
if hyprctl monitors | grep -q "Monitor DP-2"; then
    # If DP-2 is active, switch to workspace 13
    hyprctl dispatch workspace 13
else
    # If DP-2 is not active, switch to workspace 6
    hyprctl dispatch workspace 6
fi

# Check if netflix is running
if ! is_netflix_running; then
  # If netflix is not running, launch it
  hyprctl dispatch exec 'netflix'
else
  # If netflix is running, focus on its window
  hyprctl dispatch focuswindow 'Netflix'
fi
