#!/bin/bash

# Function to check if Brave browser is running
is_brave_running() {
  hyprctl clients | grep -i 'steam_app_2694490' >/dev/null
}

hyprctl dispatch workspace 7

# Check if Brave browser is running
if ! is_brave_running; then
  # If Brave is not running, launch it
  hyprctl dispatch exec 'steam -applaunch 2694490 -windowed'
else
  # If Brave is running, focus on its window
  hyprctl dispatch focuswindow 'class:^(steam_app_2694490)$'
fi
