#!/bin/bash

# Function to check if Brave browser is running
is_brave_running() {
  hyprctl clients | grep -i 'Spotify' >/dev/null
}

hyprctl dispatch workspace 6

# Check if Brave browser is running
if ! is_brave_running; then
  # If Brave is not running, launch it
  hyprctl dispatch exec 'spotify'
else
  # If Brave is running, focus on its window
  hyprctl dispatch focuswindow 'class:^(Spotify)$'
fi
