#!/bin/bash

is_kitty_running() {
  hyprctl clients | grep 'kitty-scratchpad' >/dev/null
}

if ! is_kitty_running; then
  hyprctl dispatch exec 'kitty -1 -o confirm_os_window_close=1 --class kitty-scratchpad -T kitty-scratchpad --session ~/.config/kitty/session-scratchpad'
else
  hyprctl dispatch focuswindow 'kitty-scratchpad'
fi
