#!/bin/bash

# Function to check if Netflix is running
is_netflix_running() {
  hyprctl clients | grep 'org.telegram.desktop' >/dev/null
}

hyprctl dispatch workspace 5

# Check if netflix is running
if ! is_netflix_running; then
  # If netflix is not running, launch it
  hyprctl dispatch exec 'telegram-desktop'
else
  # If netflix is running, focus on its window
  hyprctl dispatch focuswindow 'org.telegram.desktop'
fi
