#!/bin/bash

# Function to check if Zen browser is running
is_zen_running() {
  hyprctl clients | grep -i 'initialTitle: Zen Browser' >/dev/null
}

hyprctl dispatch workspace 2

# Check if Zen browser is running
if ! is_zen_running; then
  # If Zen is not running, launch it
  hyprctl dispatch exec 'zen-browser'
else
  # If Zen is running, focus on its window
  hyprctl dispatch focuswindow 'zen'
fi
