#!/usr/bin/env sh

HYPRBLUR=$(hyprctl getoption decoration:blur:enabled | awk 'NR==1{print $2}')

if [ "$HYPRBLUR" = 1 ] ; then
    hyprctl --batch "\
        keyword animations:enabled 0;\
        keyword decoration:drop_shadow 0;\
        keyword decoration:blur:enabled 0;\
        keyword general:gaps_in 0;\
        keyword general:gaps_out 0;\
        keyword general:border_size 1;\
        keyword decoration:rounding 0"

    notify-send -t 3000 "Battery Saving: On"
    exit
fi

hyprctl reload
notify-send -t 3000 "Battery Saving: Off"
