#!/bin/sh

if pgrep -x idle-handler > /dev/null; then
	notify-send -r 4444 -i /usr/share/icons/Papirus-Dark/symbolic/status/my-caffeine-on-symbolic.svg "Caffeine Enabled"
    killall swayidle
else
	notify-send -r 4444 -i /usr/share/icons/Papirus-Dark/symbolic/status/my-caffeine-off-symbolic.svg "Caffeine Disabled"
    killall swayidle
    ~/.config/hypr/scripts/idle-handler &
fi
