#!/bin/sh

if pgrep -x idle-handler > /dev/null; then
	notify-send -r 4444 -i ~/.config/mako/icons/coffee.png "Caffeine Enabled"
    killall swayidle
else
	notify-send -r 4444 -i ~/.config/mako/icons/no-caffeine.png "Caffeine Disabled"
    killall swayidle
    ~/.config/hypr/scripts/idle-handler &
fi
