#!/bin/sh

if pgrep -x idle-handler > /dev/null; then
	notify-send -t 3000 -r 4444 -i "$HOME/.config/mako/icons/coffee.png" "Caffeine Enabled"
    killall swayidle
else
	notify-send -t 3000 -r 4444 -i "$HOME/.config/mako/icons/no-caffeine.png" "Caffeine Disabled"
    killall swayidle
    ~/.config/hypr/scripts/idle-handler &
fi
