#!/bin/bash

pkill -f nwg-dock-hyprland || nwg-dock-hyprland -g "casual-kitty cava blueberry.py cpu-temp fans htop-btop-ptop nvtop wavemon protonvpn-app Chromium-browser" -i 50 -w 5 -mb 10 -ml 10 -mr 10 -c "rofi -show drun -config ~/.config/rofi/configs/config.rasi"
