#!/bin/bash

THEME='Tokyonight-Dark-BL-LB'
ICONS='Sweet-Blue'
CURSOR='Bibata-Modern-Classic'
FONT='Sans 10'

# Alternative theme
#THEME="Sweet-Dark-v40"'   # athena-sweetdark-theme
#ICONS='Papirus'
#CURSOR='Numix-Cursor-Light'


SCHEMA='gsettings set org.gnome.desktop.interface'

apply_themes() {
	${SCHEMA} gtk-theme "$THEME"
	${SCHEMA} icon-theme "$ICONS"
	${SCHEMA} cursor-theme "$CURSOR"
	${SCHEMA} font-name "$FONT"
}

apply_themes
