#!/bin/bash

THEME='NumixSolarizedDarkCyan'
ICONS='Papirus'
FONT='Sans 10'
CURSOR='Numix-Cursor-Light'

SCHEMA='gsettings set org.gnome.desktop.interface'

apply_themes() {
	${SCHEMA} gtk-theme "$THEME"
	${SCHEMA} icon-theme "$ICONS"
	${SCHEMA} cursor-theme "$CURSOR"
	${SCHEMA} font-name "$FONT"
}

apply_themes
