#!/bin/bash

THEME='Catppuccin-Mocha-Standard-Blue-Dark'
ICONS='Papirus-Dark'
FONT='MesloLGM Nerd Font 11'
CURSOR='Bibata-Modern-Classic'

SCHEMA='gsettings set org.gnome.desktop.interface'

apply_themes() {
	${SCHEMA} gtk-theme "$THEME"
	${SCHEMA} icon-theme "$ICONS"
	${SCHEMA} cursor-theme "$CURSOR"
	${SCHEMA} font-name "$FONT"
}

apply_themes
