#!/bin/sh

function handle {
  if [[ ${1:0:12} == "monitoradded" ]]; then
    hyprctl dispatch moveworkspacetomonitor "2 DP-2"
    hyprctl dispatch moveworkspacetomonitor "3 DP-2"
    hyprctl dispatch moveworkspacetomonitor "6 DP-2"
  fi
}

socat - UNIX-CONNECT:/tmp/hypr/.socket2.sock | while read line; do handle $line; done
