#!/bin/sh

function handle {
  if [[ ${1:0:12} == "monitoradded" ]]; then
    hyprctl dispatch moveworkspacetomonitor "2 2"
    hyprctl dispatch moveworkspacetomonitor "3 2"
    hyprctl dispatch moveworkspacetomonitor "6 2"
  fi
}

socat - UNIX-CONNECT:/tmp/hypr/.socket2.sock | while read line; do handle $line; done
