#!/usr/bin/bash

cd ~/videos

if ! pidof wf-recorder &>/dev/null; then
    timestamp=$(date +"%Y%m%d_%H%M%S")
    filename="recording_$timestamp.mkv"
    notify-send "wf-recorder" "Starting recording"
    wf-recorder --geometry "$(slurp)" > "$filename" 2>&1 &
else
    pkill -INT wf-recorder
    notify-send "wf-recorder" "Recording Stopped"
fi
