#!/bin/bash

iDIR="$HOME/.config/mako/icons"

time=$(date +%Y-%m-%d-%H-%M-%S)
dir="$(xdg-user-dir PICTURES)/screenshots"
file="screenshot_${time}_${RANDOM}.png"

# notify and view screenshot
# notify_cmd_shot="notify-send -h string:x-canonical-private-synchronous:shot-notify -u low -i ${iDIR}/picture.png"
notify_cmd_shot="notify-send -h string:x-canonical-private-synchronous:shot-notify -u low -i ${dir}/${file}"
notify_view() {
  #${notify_cmd_shot} "Copied to clipboard."    # doesn't ever sehow
  if [[ -e "$dir/$file" ]]; then
    ${notify_cmd_shot} "Screenshot Saved."
  else
	${notify_cmd_shot} "Copied to clipboard."
    #${notify_cmd_shot} "Screenshot Deleted."     # it's uselses
  fi
}

# Countdown
countdown() {
  for sec in $(seq $1 -1 1); do
    notify-send -h string:x-canonical-private-synchronous:shot-notify -t 1000 -i "$iDIR"/timer.png "Taking shot in : $sec"
    sleep 1
  done
}

# -----------------------------------------------------
# COUNTDOWN FULLSCREEN
# -----------------------------------------------------

shot5() {
  countdown '5'
  sleep 1 && cd ${dir} && grim - | tee "$file" | wl-copy
  notify_view
}

shot10() {
  countdown '10'
  sleep 1 && cd ${dir} && grim - | tee "$file" | wl-copy
  notify_view
}

# -----------------------------------------------------
# AREA
# -----------------------------------------------------
# Picture preview in notify-send can only be done when the screenshot is saved 
# using: | tee "$file" | wl-copy

shotareaclip() {
  cd ${dir} && grim -g "$(slurp -b 1B1F28CC -c E06B74ff -s C778DD0D -w 2)" /tmp/screenshot.png && wl-copy < /tmp/screenshot.png
  notify_view
}

shotareasave() {
  cd ${dir} && grim -g "$(slurp -b 1B1F28CC -c E06B74ff -s C778DD0D -w 2)" - | tee "$file" | wl-copy
  notify_view
}

shotareaedit() {
  cd ${dir} && grim -g "$(slurp -b 1B1F28CC -c E06B74ff -s C778DD0D -w 2)" - | swappy -f - && wl-paste --no-newline | wl-copy --type image/png && wl-paste --no-newline > /tmp/screenshot.png
  notify_view
}

# -----------------------------------------------------
# WINDOWS
# -----------------------------------------------------

shotwinclip() {
  w_pos=$(hyprctl activewindow | grep 'at:' | cut -d':' -f2 | tr -d ' ' | tail -n1)
  w_size=$(hyprctl activewindow | grep 'size:' | cut -d':' -f2 | tr -d ' ' | tail -n1 | sed s/,/x/g)
  cd ${dir} && grim -g "$w_pos $w_size" - | tee "$file" | wl-copy
  notify_view
}

shotwinsave() {
  w_pos=$(hyprctl activewindow | grep 'at:' | cut -d':' -f2 | tr -d ' ' | tail -n1)
  w_size=$(hyprctl activewindow | grep 'size:' | cut -d':' -f2 | tr -d ' ' | tail -n1 | sed s/,/x/g)
  cd ${dir} && grim -g "$w_pos $w_size" - | tee "$file" | wl-copy
  notify_view
}

shotwinedit() {
  w_pos=$(hyprctl activewindow | grep 'at:' | cut -d':' -f2 | tr -d ' ' | tail -n1)
  w_size=$(hyprctl activewindow | grep 'size:' | cut -d':' -f2 | tr -d ' ' | tail -n1 | sed s/,/x/g)
  cd ${dir} && grim -g "$w_pos $w_size" - | tee "$file" | wl-copy
  notify_view
}

# -----------------------------------------------------
# FULLSCREEN
# -----------------------------------------------------

shotfullclip() {
  cd ${dir} && grim - | wl-copy
  notify_view
}

shotfullsave() {
  cd ${dir} && grim - | tee "$file" | wl-copy
  notify_view
}

shotfulledit() {
  cd ${dir} && grim - | swappy -f -
  notify_view
}


# -----------------------------------------------------
# COMMAND OPTIONS
# -----------------------------------------------------

if [[ ! -d "$dir" ]]; then
  mkdir -p "$dir"
fi

if [[ "$1" == "--full" ]]; then
  shotfullclip
elif [[ "$1" == "--full-save" ]]; then
  shotfullsave
elif [[ "$1" == "--full-edit" ]]; then
  shotfulledit
elif [[ "$1" == "--win" ]]; then
  shotwinclip
elif [[ "$1" == "--full-save" ]]; then
  shotwinsave
elif [[ "$1" == "--full-edit" ]]; then
  shotwinedit
elif [[ "$1" == "--area" ]]; then
  shotareaclip
elif [[ "$1" == "--area-save" ]]; then
  shotareasave
elif [[ "$1" == "--area-edit" ]]; then
  shotareaedit
elif [[ "$1" == "--in5" ]]; then
  shot5
elif [[ "$1" == "--in10" ]]; then
  shot10
else
  echo -e "Available Options : --now --in5 --in10 --win --area --area-edit --area-save"
fi

exit 0
