#!/bin/sh

PATH=$HOME/.config/hypr/scripts:$HOME/.config/zsh/bash-scripts:$HOME/.local/bin:$HOME/.config/.local/bin:$HOME/.config/rofi/applets/bin:$HOME/.config/rofi/launcher:$HOME/.config/rofi/wifi:$HOME/.config/node_modules/.bin:$PATH
export PATH

cd ~ || exit

# Essential Vars
export HYPRLAND_LOG_WLR=1                             # Log WLR errors and logs to the hyprland log
export QT_QPA_PLATFORM="wayland;xcb"                  # Tell QT applications to use the Wayland backend, and fall back to x11 if Wayland is unavailable
export QT_QPA_PLATFORMTHEME=qt5ct                     # Tells QT based applications to pick your theme from qt5ct
export GDK_BACKEND="wayland,x11"                      # Controls how GTK apps run
export SDL_VIDEODRIVER=wayland                        # Run SDL2 applications on Wayland
export CLUTTER_BACKEND=wayland                        # Force Clutter applications to try and use the Wayland backend
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1          # Disables window decorations on QT applications
export QT_AUTO_SCREEN_SCALE_FACTOR=1                  # enables automatic scaling, based on the monitor’s pixel density
export XDG_SESSION_TYPE=wayland                       # This effects Qt and other non-GTK toolkits
XDG_CURRENT_DESKTOP=Hyprland                          # Sanity check for Hyprland on Wayland
XDG_CURRENT_DESKTOP=Hyprland                          # Sanity check for Hyprland on Wayland
export MUTTER_DEBUG_ENABLE_ATOMIC_KMS=0               # Fix slightly sloppy mouse response issue
export CLUTTER_PAINT=disable-dynamic-max-render-time  # Get a smoother frame rate
export _JAVA_AWT_WM_NONREPARENTING=1                  # Java apps do not support Wayland natively
export XCURSOR_THEME=Numix-Cursor-Light               # Cursor theme for Xwayland
export XCURSOR_SIZE=24                                # Cursor size for Xwayland
export WLR_NO_HARDWARE_CURSORS=1                      # Cursor does not need hardware
export MOZ_ENABLE_WAYLAND=1                           # Enables Wayland for Mozilla products
export MOZ_DISABLE_RDD_SANDBOX=1                      # Disable RDD sandbox in firefox
export KITTY_ENABLE_WAYLAND=1                         # Sanity check for kitty on Wayland
export MOZ_DBUS_REMOTE=1
export BEMENU_BACKEND=wayland
export ECORE_EVAS_ENGINE=wayland_egl
export ELM_ENGINE=wayland_egl
export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=dbus
export QT_IM_MODULE=ibus

exec Hyprland
