#!/bin/sh

PATH=$HOME/.config/hypr/scripts:$HOME/.config/zsh/bash-scripts:$HOME/.config/.local/bin:$HOME/.config/rofi/applets/bin:$HOME/.config/rofi/launcher:$HOME/.config/rofi/wifi:$HOME/.emacs.d/bin:$PATH
export PATH

cd ~ || exit

export HYPRLAND_LOG_WLR=1                             # Log WLR errors and logs to the hyprland log
export QT_QPA_PLATFORMTHEME=qt5ct                     # Tells QT based applications to pick your theme from qt5ct
export SDL_VIDEODRIVER=wayland                        # Run SDL2 applications on Wayland
export CLUTTER_BACKEND=wayland                        # Force Clutter applications to try and use the Wayland backend
export QT_QPA_PLATFORM="wayland;xcb"                  # Tell QT applications to use the Wayland backend, and fall back to x11 if Wayland is unavailable
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1          # Disables window decorations on QT applications
export QT_AUTO_SCREEN_SCALE_FACTOR=1                  # enables automatic scaling, based on the monitor’s pixel density
export XDG_CURRENT_DESKTOP=Hyprland                   # XDG specific var for sanity check
export XDG_SESSION_DESKTOP=Hyprland                   # XDG specific var for sanity check
export GDK_BACKEND=wayland                            # Controls how GTK apps run
export XDG_SESSION_TYPE=wayland                       # This effects Qt and other non-GTK toolkits
export MOZ_ENABLE_WAYLAND=1                           # Enables Wayland for Mozilla products
export MUTTER_DEBUG_ENABLE_ATOMIC_KMS=0               # Fix slightly sloppy mouse response issue
export CLUTTER_PAINT=disable-dynamic-max-render-time  # Get a smoother frame rate
export _JAVA_AWT_WM_NONREPARENTING=1                  # Java apps don’t support Wayland natively
export XCURSOR_THEME=Numix-Cursor-Light               # Cursor theme for Xwayland
export XCURSOR_SIZE=24                                # Cursor size for Xwayland
export WLR_NO_HARDWARE_CURSORS=1                      # Cursor doesn't need hardware
export MOZ_DISABLE_RDD_SANDBOX=1                      # Disable RDD sandbox in firefox
export CLUTTER_PAINT=disable-dynamic-max-render-time  # Get a smoother frame rate

exec Hyprland
