#!/bin/bash

# Toggle VPN
if [ $(ip a s | grep tun0 | grep inet | awk '{print $2;}' | cut -d . -f2 | tr -d '\n' | wc -c) -eq 0 ]; then
  notify-send -u low -t 4000 -i "$HOME/.config/mako/icons/vpn.png" "VPN is active"
  kitty -1 -T kitty-vpn --class kitty-vpn -e sudo openvpn ~/downloads/*.ovpn
elif [ $(ip a s | grep tun0 | grep inet | awk '{print $2;}' | cut -d . -f2 | tr -d '\n' | wc -c) -eq 2 ]; then
  kill -9 $(ps aux | grep kitty-vpn)
  notify-send -u low -t 4000 -i "$HOME/.config/mako/icons/vpn.png" "VPN is down"
fi

