#!/bin/bash

# Directory where the script is located
cd "$HOME/.config/eww"

# Name of the Python script
script_name="waifupics.py"

# Kill the script if already running
if pgrep -f "$script_name" >/dev/null; then
    pkill -9 -f "$script_name"
    notify-send -t 3000 "Waifu script stopped"
else
    # Notify user that the script is running
    notify-send -t 3000 "Waifu script running"

    # Run the script for 15 minutes
    runtime=$((SECONDS+900))

    while [ $SECONDS -lt $runtime ]; do
        echo "Starting waifupics.py..."
        python $script_name &
        echo "waifupics.py has been started."

        # Sleep for 3 seconds before running the script again
        sleep 3
    done

    # Notify user that the script has finished
    notify-send "Waifu has finished running"
fi
