#!/bin/bash

# Cache file for holding the current wallpaper
cache_file="$HOME/.cache/current_wallpaper"
rasi_file="$HOME/.cache/current_wallpaper.rasi"

# Create cache file if not exists
if [ ! -f $cache_file ] ;then
    touch $cache_file
    echo "$HOME/pictures/wallpapers/default.jpg" > "$cache_file"
fi

# Create rasi file if not exists
if [ ! -f $rasi_file ] ;then
    touch $rasi_file
    echo "* { current-image: url(\"$HOME/pictures/wallpapers/default.jpg\", height); }" > "$rasi_file"
fi

current_wallpaper=$(cat "$cache_file")

case $1 in

    # Load wallpaper from .cache of last session 
    "init")
        if [ -f ~/.cache/current_wallpaper.jpg ]; then
            wal -q -i $current_wallpaper
        else
            wal -q -i ~/pictures/wallpapers/wm-wallpapers
        fi
		;;

    # Select wallpaper with rofi
    "select")
        selected=$( find "$HOME/pictures/wallpapers/wm-wallpapers" -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" \) -exec basename {} \; | sort -R | while read rfile
        do
            echo -en "$rfile\x00icon\x1f$HOME/pictures/wallpapers/wm-wallpapers/${rfile}\n"
        done | rofi -dmenu -replace -config ~/.config/rofi/configs/config-wallpaper.rasi)
        if [ ! "$selected" ]; then
            echo "No wallpaper selected"
            exit
        fi

        wal -q -i ~/pictures/wallpapers/wm-wallpapers/$selected
		;;

    # Randomly select wallpaper 
    *)
        wal -q -i ~/pictures/wallpapers/wm-wallpapers
		;;

esac

# ----------------------------------------------------- 
# Load current pywal color scheme
# ----------------------------------------------------- 
source "$HOME/.cache/wal/colors.sh"
echo "Wallpaper: $wallpaper"

# ----------------------------------------------------- 
# Copy selected wallpaper into .cache folder
# ----------------------------------------------------- 
echo "$wallpaper" > "$cache_file"
echo "* { current-image: url(\"$wallpaper\", height); }" > "$rasi_file"

# ----------------------------------------------------- 
# Get wallpaper image name to display
# ----------------------------------------------------- 
newwall=$(echo $wallpaper | sed "s|$HOME/pictures/wallpapers/wm-wallpapers||g")

# ----------------------------------------------------- 
# Reload waybar with new colors
# -----------------------------------------------------
~/.config/hypr/scripts/waybar-reset-theme

# ----------------------------------------------------- 
# Set the new wallpaper
# -----------------------------------------------------
#transition_type="wipe"
#transition_type="outer"
transition_type="random"

swww img $wallpaper \
    --transition-bezier .43,1.19,1,.4 \
    --transition-fps=60 \
    --transition-type=$transition_type \
    --transition-duration=0.7
#    --transition-pos "$( hyprctl cursorpos )"

# ----------------------------------------------------- 
# Send notification
# ----------------------------------------------------- 
if [ "$1" == "init" ] ;then
    echo ":: Init"
else
    sleep 1
    notify-send "Colors and Wallpaper updated" "with image $newwall"
fi

echo "DONE!"
