#!/usr/bin/bash

# Terminate already running bar instances
killall -q waybar

# Wait until the waybar processes have been shut down
while pgrep -x waybar >/dev/null; do sleep 1; done

# Launch waybar
waybar -c ~/.config/waybar/config -s ~/.config/waybar/style.css
