;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
		er/mark-symbol
		org-kill-line
		org-self-insert-command
		org-toggle-item
		scroll-up-line
		smart-hungry-delete-backward-char
		smart-hungry-delete-forward-char
		surround-bold
		tl/backward-char-skip-invisible
		tl/backward-entire-word
		tl/forward-char-skip-invisible
		tl/forward-entire-word
		tl/paste-from-system-clipboard
		tl/smart-move-beginning-of-line
		tl/smart-move-end-of-line
		toggle-mark-command
		))

(setq mc/cmds-to-run-once
      '(
		basic-save-buffer
		corfu-quit
		god-local-mode
		org-backward-sentence
		org-forward-sentence
		repeat
		tl/toggle-letter-case
		))
