;;   -*- lexical-binding: t; -*-
;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
		tl/smart-move-beginning-of-line
		tl/smart-move-end-of-line
		))

(setq mc/cmds-to-run-once
      '(
		god-local-mode
		org-backward-sentence
		org-forward-sentence
		))
