[General]
# Path to the wallpaper. If it's in the assets folder, use "assets/background.jpg"
background=assets/background.jpg

# Material You-like colors (we can refine these)
primaryColor=#E3E3DC
accentColor=#A9C78F
autoColor=true
use24HourClock=false
backgroundColor=#1A1C18
textColor=#E3E3DC

# Font settings
fontFamily=JetBrainsMonoNL
fontSize=10

