#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# ----------- AUTOSTART -----------
# VBox
VBoxClient --clipboard &
VBoxClient --seamless &
VBoxClient --checkhostversion &
# Bare Metal
picom --experimental-backends &
nitrogen --restore &
exec --no-startup -id dunst &
udiskie &
bash ~/.config/polybar/launch.sh
#Network
#nm-applet &
# Bluetooth
#blueman-applet &
# systray battery icon
## cbatticon -u 5 &
# systray volume
#volumeicon &

# ----------- OTHER -----------
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
