#! /bin/sh

# ----------- autostart -----------
pgrep -x sxhkd > /dev/null || sxhkd &
# VBox
VBoxClient --clipboard &
VBoxClient --seamless &
VBoxClient --checkhostversion &
# Bare Metal
picom --experimental-backends &
nitrogen --restore &
exec --no-startup -id dunst &
udiskie &
bash ~/.config/polybar/launch.sh
#Network
#nm-applet &
# Bluetooth
#blueman-applet &

# ----------- config -----------
bspc monitor -d I II III IV V VI VII VIII
#bspc monitor DP-1 -d V VI VII

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#bspc config focused_border_color     "#26F0F1"
#bspc config normal_border_color      "#202A25"

# ----------- start defined app on corresponding workspace -----------
# ----------- use xprop utility for checking class names and use it instaed of names such as Gimp -----------
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
