active_border_color    {foreground}
inactive_border_color {background}

cursor             {cursor}
cursor_trail_color {cursor}

active_tab_foreground     {background}
active_tab_background     {foreground}
inactive_tab_foreground   {foreground}
inactive_tab_background   {background}
