#!/bin/bash

clear
cat <<"EOF"
 ___           _        _ _ _               _____           _     
|_ _|_ __  ___| |_ __ _| | (_)_ __   __ _  |_   _|__   ___ | |___ 
 | || '_ \/ __| __/ _` | | | | '_ \ / _` |   | |/ _ \ / _ \| / __|
 | || | | \__ \ || (_| | | | | | | | (_| |   | | (_) | (_) | \__ \
|___|_| |_|___/\__\__,_|_|_|_|_| |_|\__, |   |_|\___/ \___/|_|___/
                                    |___/                         

EOF

# Prompt the user
read -p "This will take minimum 30 minutes, continue? (y/n) " answer
if [[ "$answer" != "y" ]]; then
    echo "No changes made."
    exit 0
fi

bloat=(
  "swaylock"
  "swayidle"
  "garuda-system-maintenance"
  "garuda-hyprland-settings"
  "garuda-fish-config"
  "garuda-boot-options"
  "garuda-browser-settings"
  "firedragon"
  "garuda-gamer"
  "garuda-network-assistant"
  "garuda-setup-assistant"
  "garuda-welcome"
  "garuda-settings-manager"
  "garuda-assistant"
  "alacritty"
  "deluge-gtk"
  "eog"
  "qualculate-gtk"
  "gestures"
  "mako"
  "evince"
  "foot"
  "fsearch"
  "geany"
  "meld"
  "pace"
  "ranger"
  "gnome-system-monitor"
  "gnome-logs"
  "xfce4-terminal"
)

packages=(
  "hyprland"
  "hyprlock"
  "xdg-desktop-portal-hyprland"
  "xdg-desktop-portal-gtk"
  "brave-bin"
  "python-click"
  "python-tomlkit"
  "python-click-aliases"
  "neovim"
  "thefuck"
  "zoxide"
  "lsd"
  "pkgfile"
  "trash-cli"
  "mtools"
  "swaybg"
  "wdisplays"
  "ripgrep"
  "perl-image-exiftool"
  "xorg-xhost"
  "the_silver_searcher"
  "irqbalance"
  "zenpower3-dkms"
  "acpi"
  "dkms"
  "emacs-wayland"
  "duf"
  "ncdu"
  "rlwrap"
  "speedtest-cli"
  "gnome-weather"
  "gnome-maps"
  "gnome-keyring"
  "fd"
  "trash-cli"
  "cpupower"
  "mingw-w64"
  "zathura"
  "zathura-pdf-poppler"
  "grc"
  "udiskie"
  "usbutils"
  "wf-recorder"
  "net-tools"
  "upower"
  "apparmor"
  "thefuck"
  "libsecret"
  "chafa"
  "alsa-utils"
  "yt-dlp"
  "pipewire"
  "pipewire-alsa"
  "wireplumber"
  "gtk-engine-murrine"
  "freerdp2"
  "proxychains"
  "proton-vpn-gtk-app"
  "libayatana-appindicator"
  "dunst"
  "libnotify"
  "zsh"
  "zsh-autosuggestions"
  "zsh-completions"
  "zsh-history-substring-search"
  "zsh-syntax-highlighting"
  "rsync"
  "git"
  "cliphist"
  "fortune-mod"
  "tty-clock"
  "wlr-randr-git"
  "cowsay"
  "ffmpeg"
  "grim"
  "gvfs"
  "figlet"
  "lolcat"
  "neofetch"
  "inxi"
  "findutils"
  "kitty"
  "pavucontrol"
  "playerctl"
  "python-requests"
  "python-pip"
  "qt5ct"
  "qt6ct"
  "slurp"
  "waybar"
  "wget"
  "wl-clipboard"
  "pkg-config"
  "wavemon"
  "wlogout"
  "xdg-user-dirs"
  "xdg-utils"
  "yad"
  "brightnessctl"
  "btop"
  "eog"
  "mpv"
  "mpv-mpris"
  "acpi"
  "acpid"
  "nvtop"
  "pamixer"
  "xcp"
  "xh"
  "wire-desktop"
  "exa"
  "bat"
  "expac"
  "freetube"
	"gnome-calculator"
  "dog"
  "ripgrep"
	"keepassxc"
  "rofi-lbonn-wayland-git"
  "swaybg"
  "ananicy-cpp"
  "nohang"
  "imagemagick"
  "swappy"
  "thunar"
  "kvantum-qt5"
  "git-delta"
  "translate-shell"
  "dust"
	"ngrok"
	"firewalld"
	"sd"
	"pv"
  "cpufetch"
	"udev-block-notify-git"
  "cmatrix-git"
  "cava-git"
  "python-pywal"
  "moar"
  "cheat-bin"
	"xdg-ninja-git"
	"dragon-drop"
	"noise-suppression-for-voice-git"
)

extra=(
	"toilet"
	"caffeine-ng"
	"asciiquarium-transparent-git"
  "fireplace-git"
	"trizen"
	"sushi"
	"wildmidi"
	"timidity++"
	"vnstat"
	"taskell"
	"zenity"
	"progress"
	"tokei"
	"procs"
	"hub"
	"songrec"
	"python-pyopenssl"
	"python-pycryptodomex"
	"graphviz"
	"nyancat"
	"superproductivity-bin"
  "musikcube"
	"android-tools"
	"blanket"
	"swayimg"
	"appmenu-gtk-module"
	"libdbusmenu-glib"
	"python-pywhat"
	"tabbed-git"
	"sway-audio-idle-inhibit-git"
	"tabbed-git"
	"ffsend-bin"
	"ascii-image-converter-git"
	"boxes"
	"sysz"
	"shellcheck-bin"
	"net-snmp"
	"nodejs-git-stats"
)

# First you have to uninstall the bloat
echo "Removing bloat..."
_uninstallPackagesParu "${bloat[@]}"

# Install packages
echo "Installing packages..."
_installPackagesParu "${packages[@]}"
#_installPackagesParu "${extra[@]}"

# Wait 2 sec before clear so user knows what happened
sleep 2
