# TV config
#monitor = HDMI-A-1, 3840x2160@120, auto, 2
monitor = DP-1, 2560x1440@180, 1920x0, 1.25
monitor = HDMI-A-1, 1920x1080@144, 0x0, 1

# Special workspaces
workspace=special:comma, on-created-empty:~/.config/hypr/ws-scripts/ws-agenda                    # Super + M
workspace=special:scratchpad, on-created-empty:~/.config/hypr/ws-scripts/ws-monitoring           # Super + Comma
workspace=special:floating, on-created-empty: nautilus                                           # Super + N
workspace=special:period, on-created-empty: bash -c "blueman-manager & blanket & pavucontrol & kitty -T cava --class cava -e cava"                                           # Super + Period
