#!/bin/bash

# ANSI color codes
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

mega-sync -d /home/twilight/desktop/projects
mega-sync -d /home/twilight/documents/openvpn
mega-sync -d /home/twilight/documents/pdfs
mega-sync -d /home/twilight/.ssh

echo -e "${GREEN}All specified directories have been unsynced.${NC}"

# Log out
#mega-logout
#echo
#echo -e "${GREEN}Logged out successfully.${NC}"
