#!/bin/bash

# ANSI color codes
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Check if the user is already logged in
login_status=$(mega-login 2>&1)

if echo "$login_status" | grep -q "Already logged in. Please log out first."; then
    echo -e "${GREEN}You are already logged in. Starting synchronization...${NC}"

    # Synchronize directories
    mega-sync $HOME/documents/pdfs /SYNCED-DATA/documents/pdfs
    mega-sync $HOME/.ssh/ /SYNCED-DATA/.ssh/

    # Sync Freetube
    mega-put ~/.config/FreeTube/*.db /SYNCED-DATA/.config/FreeTube/

    echo -e "${GREEN}Synchronization completed.${NC}"
    echo -e "${GREEN}Please run 'mega-sync-off' to turn off syncing in order to keep a backup and log out.${NC}"
    echo
    echo -e "${BLUE}You can run 'watch mega-sync' command to check current syncing.${NC}"
else
    echo -e "${RED}Please log in using 'mega-login <email> <pass>' and try again.${NC}"
fi
