#!/bin/bash

# Warning: Before running the script make sure you have installed dkms module and kernel headers packages and rebooted
# and read instructions in github repo: debian-setup/assets/notes/omen-keyboard.org
# Otherwise the script will not work

# Prompt the user for a color hex value without a hashtag
read -p "Enter a color hex value (e.g., RRGGBB): " color_value

# Validate the input to ensure it is a valid hex color value
if [[ ! "$color_value" =~ ^([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$ ]]; then
	echo "Invalid color hex value. Please enter a valid value (e.g., RRGGBB)."
	exit 1
fi

# Add a hashtag to the color value
color_value="$color_value"

# Write the color value to the specified file
sudo bash -c "echo \"$color_value\" >/sys/devices/platform/hp-wmi/rgb_zones/zone00"
sudo bash -c "echo \"$color_value\" >/sys/devices/platform/hp-wmi/rgb_zones/zone01"
sudo bash -c "echo \"$color_value\" >/sys/devices/platform/hp-wmi/rgb_zones/zone02"
sudo bash -c "echo \"$color_value\" >/sys/devices/platform/hp-wmi/rgb_zones/zone03"

echo "Color value set to $color_value successfully."
