#!/bin/bash

# Check the current status of the fan boost
status=$(sudo omen-fan i | grep 'Service Status : Running')

# Toggle the fan boost based on the current status
if [ -n "$status" ]; then
    sudo omen-fan e 0
    echo "Fan Service Running."
    notify-send "Fan Service" "Fan Service Running."
else
    sudo omen-fan e 1
    echo "Fan Service Stopped."
    notify-send "Fan Service" "Fan Service Stopped."
fi
